replicaCount: 3
image:
  repository: juniorcloud/bitnet-mlx
  pullPolicy: IfNotPresent
  tag: "v16.0.0"
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"
modelAssets:
  hostPath: "/mnt/data/models"
